# Generated by Django 4.2.27 on 2026-01-16 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_type', models.CharField(choices=[('PAIN', 'Dolor'), ('FATIGUE', 'Fatiga'), ('NAUSEA', 'Náusea'), ('VOMITING', 'Vómito'), ('FEVER', 'Fiebre'), ('INSOMNIA', 'Insomnio'), ('APPETITE_LOSS', 'Pérdida de apetito'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de síntoma')),
                ('intensity', models.IntegerField(help_text='Intensidad de 1 a 10', verbose_name='Intensidad')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('location', models.CharField(blank=True, help_text='Para dolor: ubicación del dolor', max_length=100, verbose_name='Ubicación')),
                ('reported_via', models.CharField(choices=[('CHAT', 'Chat con Lia'), ('FORM', 'Formulario'), ('VOICE', 'Memo de voz')], default='FORM', max_length=10, verbose_name='Reportado vía')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('doctor_notes', models.TextField(blank=True, verbose_name='Notas del médico')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='symptom_reports', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
                ('related_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.chatinteraction', verbose_name='Interacción de chat relacionada')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_symptoms', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Reporte de Síntoma',
                'verbose_name_plural': 'Reportes de Síntomas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('DIAGNOSIS', 'Diagnóstico'), ('TREATMENT', 'Tratamiento'), ('SURGERY', 'Cirugía'), ('SYMPTOM', 'Síntoma'), ('APPOINTMENT', 'Cita Médica'), ('LAB_RESULT', 'Resultado de Laboratorio'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de evento')),
                ('event_description', models.TextField(verbose_name='Descripción del evento')),
                ('event_date', models.DateField(verbose_name='Fecha del evento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timeline_events', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_timeline', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Evento de Línea de Tiempo',
                'verbose_name_plural': 'Eventos de Línea de Tiempo',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('SYMPTOM_SEVERE', 'Síntoma Severo'), ('EMOTION_CRISIS', 'Crisis Emocional'), ('MISSED_CHECKIN', 'Check-in Perdido'), ('CHAT_RISK', 'Riesgo Detectado en Chat'), ('MANUAL', 'Manual')], max_length=20, verbose_name='Tipo de alerta')),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], max_length=10, verbose_name='Severidad')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('suggested_action', models.TextField(blank=True, verbose_name='Acción sugerida')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resuelta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas de resolución')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email enviado')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
                ('related_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.chatinteraction', verbose_name='Chat relacionado')),
                ('related_symptom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.symptomreport', verbose_name='Síntoma relacionado')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Resuelta por')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='symptomreport',
            index=models.Index(fields=['patient', '-timestamp'], name='clinical_sy_patient_f2636d_idx'),
        ),
        migrations.AddIndex(
            model_name='symptomreport',
            index=models.Index(fields=['symptom_type', 'intensity'], name='clinical_sy_symptom_bd6db8_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['patient', 'is_resolved', '-created_at'], name='clinical_al_patient_a1c620_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', 'is_resolved'], name='clinical_al_severit_30fc1e_idx'),
        ),
    ]
