# Generated by Django 4.2.27 on 2026-01-16 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(verbose_name='Mensaje del usuario')),
                ('bot_response', models.TextField(verbose_name='Respuesta de Lia')),
                ('sentiment_flag', models.CharField(choices=[('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positivo'), ('CONCERN', 'Preocupación'), ('ALERT', 'Alerta')], default='NEUTRAL', max_length=10, verbose_name='Indicador de sentimiento')),
                ('risk_keywords_detected', models.JSONField(default=list, verbose_name='Palabras clave de riesgo detectadas')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('emotion_scores', models.JSONField(blank=True, null=True, verbose_name='Puntuaciones de emoción (ML)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_interactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Interacción de Chat',
                'verbose_name_plural': 'Interacciones de Chat',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VoiceMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='voice_memos/%Y/%m/%d/', verbose_name='Archivo de audio')),
                ('transcription', models.TextField(blank=True, verbose_name='Transcripción')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='Duración (segundos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('related_interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_memos', to='chatbot.chatinteraction', verbose_name='Interacción relacionada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_memos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Memo de Voz',
                'verbose_name_plural': 'Memos de Voz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatinteraction',
            index=models.Index(fields=['user', '-timestamp'], name='chatbot_cha_user_id_c043a8_idx'),
        ),
        migrations.AddIndex(
            model_name='chatinteraction',
            index=models.Index(fields=['sentiment_flag'], name='chatbot_cha_sentime_26c1b3_idx'),
        ),
    ]
