# Generated by Django 4.2.27 on 2026-01-16 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_text', models.TextField(verbose_name='Recomendación')),
                ('category', models.CharField(choices=[('EXERCISE', 'Ejercicio'), ('MEDITATION', 'Meditación'), ('SOCIAL', 'Actividad Social'), ('READING', 'Lectura'), ('HOBBY', 'Hobby'), ('NUTRITION', 'Nutrición'), ('SLEEP', 'Sueño'), ('OTHER', 'Otro')], max_length=15, verbose_name='Categoría')),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='Generado por IA')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('patient_completed', models.BooleanField(default=False, verbose_name='Completada por paciente')),
                ('patient_helpful', models.BooleanField(blank=True, null=True, verbose_name='Fue útil')),
                ('created_by_psychologist', models.ForeignKey(blank=True, limit_choices_to={'role': 'PSYCHOLOGIST'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Creado por psicólogo/a')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Recomendación',
                'verbose_name_plural': 'Recomendaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_score', models.IntegerField(help_text='Estado de ánimo general (1=Muy mal, 10=Excelente)', verbose_name='Estado de ánimo')),
                ('anxiety_score', models.IntegerField(help_text='Nivel de ansiedad (1=Sin ansiedad, 10=Ansiedad extrema)', verbose_name='Nivel de ansiedad')),
                ('energy_score', models.IntegerField(help_text='Nivel de energía (1=Agotado/a, 10=Muy energizado/a)', verbose_name='Nivel de energía')),
                ('pain_emotional_impact', models.IntegerField(blank=True, help_text='Impacto emocional del dolor (1=Bajo, 10=Alto)', null=True, verbose_name='Impacto emocional del dolor')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='emotion_logs', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Registro Emocional',
                'verbose_name_plural': 'Registros Emocionales',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_share_with_doctor', models.BooleanField(default=True, verbose_name='Compartir datos clínicos con médico')),
                ('can_share_chat_with_doctor', models.BooleanField(default=False, verbose_name='Compartir conversaciones de chat con médico')),
                ('can_share_with_psychologist', models.BooleanField(default=True, verbose_name='Compartir datos emocionales con psicólogo/a')),
                ('can_use_for_research', models.BooleanField(default=False, verbose_name='Uso de datos para investigación (anonimizados)')),
                ('consent_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de consentimiento')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('patient', models.OneToOneField(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='consent_record', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Registro de Consentimiento',
                'verbose_name_plural': 'Registros de Consentimiento',
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_type', models.CharField(choices=[('DAILY', 'Diario'), ('WEEKLY', 'Semanal')], default='DAILY', max_length=10, verbose_name='Tipo de check-in')),
                ('scheduled_date', models.DateField(verbose_name='Fecha programada')),
                ('completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
                ('related_emotion_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psychosocial.emotionlog', verbose_name='Registro emocional relacionado')),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-ins',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.AddIndex(
            model_name='emotionlog',
            index=models.Index(fields=['patient', '-timestamp'], name='psychosocia_patient_5a5519_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together={('patient', 'scheduled_date', 'checkin_type')},
        ),
    ]
